### ISSUE TITLE
Release code

### ISSUE THREAD

**Issue by YipingNUS** [epfl-dlab/pairformance#1]
Hi, interesting paper challenging the status quo of standard evaluation! May I know if there's a timeline to release the library? It'll benefit the NLP community greatly if you can publicize it and drive more adoption.

**Comment by PeyrardM** [comment]
Hi, thank you for your interest in the work! 
We are releasing it the code by end of the month. 
Currently, we are adding some diagnostic capabilities.

**Comment by PeyrardM** [comment]
The first version of the tool has been released
